<<<<<<< HEAD
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: node script.js
=======
name: Inject API Key

on: [push]

jobs:
  inject:
    runs-on: ubuntu-latest

    steps:
    - name: Inject API key into environment
      run: echo "API_KEY=${{ secrets.OPENAI_KEY }}" >> $GITHUB_ENV
>>>>>>> a7a2c26b6b4d5e713fe36163b29898026acdcdf0
